; generated by Slic3r Prusa Edition 1.42.0-alpha7+linux64 on 2019-04-10 at 14:15:15

;

; external perimeters extrusion width = 0.40mm
; perimeters extrusion width = 0.40mm
; infill extrusion width = 0.40mm
; solid infill extrusion width = 0.40mm
; top infill extrusion width = 0.40mm
; support material extrusion width = 0.40mm
; first layer extrusion width = 0.40mm

M73 P0 R91
M107
M117 Homing
G32

M83  ; extruder relative mode

;M140 S60 ; set bed temp
;M190 S60 ; wait for bed temp

M104 S215 ; set extruder temp
M109 S215 ; wait for extruder temp
G1 E-5  F1000.0 ;
M73 P0 R91

;G28 W ; home all without mesh bed level
;G80 ; mesh bed leveling

;G1 Y-3.0 F1000.0 ; go outside print area
G1 X0 Y5 F1000.0
G1 Z0 F1000.0

G92 E0.0
G1 X60.0 E9.0  F1000.0 ; intro line
G1 X100.0 E12.5  F1000.0 ; intro line
G92 E0.0

M221 S95
;Filament gcode
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.3

M117 START
G1 E-0.80000 F6000.00000
G1 Z0.0 F1000.00000
